### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Arg022** [CyanVoxel/Obsidian-Notebook-Themes#4]
How can i change the background of a single note but instead of change the color i put an image? [ sorry for the question  :'( ]

**Comment by CyanVoxel** [comment]
No worries! I'd be happy to help. To be clear, are you looking to use an image for the background of a note instead of a solid color?

**Comment by Arg022** [comment]
Yes, exactly, I'm trying to create some gaming-themed notes with an image or pattern background, but I'm having some issues. Thanks anyway for responding earlier.
