### ISSUE TITLE
not a issue! just a query

### ISSUE THREAD

**Issue by Rust-soham** [CyanVoxel/Obsidian-Notebook-Themes#5]
hey man! that last video was great.

But one thing I struggled with was turning on the JetBrains font, watched every video, forum answers, all of that jazz. but even after making the css snippet for the fonts, it can't seem to work.

it would be great if you can make a video around that. (or any kind of help would be fine)

I would've dm'd you on ig but it's off I guess.

Have a great day!

**Comment by CyanVoxel** [comment]
Hey there! You know what's funny, someone else actually DM'd me on IG a few days ago asking the same thing! (it went through as a message request and I nearly didn't see it, so I'll try and open up my settings a bit more)

In his case, we were able to fix it when he switched from a theme that was interfering with it. In case it's not as simple for you, I'd recommend checking to make sure that the font is at the top (or is the only) of the lists in the individual font sections. Also make sure that you're applying the font to the correct sections you want (interface, text, monospace, or all) - but I'm guessing you've probably already tried that.
![image](https://github.com/CyanVoxel/Obsidian-Notebook-Themes/assets/46939827/145e74cf-dc97-4637-94f1-ad5baa788d23)
